#!/bin/bash


# set year, yy, month and days for periods defined here
# a specific period x can be accesed by calling the scripts with argument "periodx"
function get_dates_for_periods {
     
     period=$1


# period1 (13.-20.2 2019)
if [ $period = period1 ];
then
    year=2019
    yy=19
    month=02
    days=(13 14 15 16 17 18 19 20)
fi

# period2 (23.-29.6 2019)
if [ $period = period2 ];
then
    year=2019
    yy=19
    month=06
    days=(23 24 25 26 27 28 29)
fi

# period3 (1.-7.12 2018)
if [ $period = period3 ];
then    
    year=2018
    yy=18
    month=12
    days=(01 02 03 04 05 06 07)
fi

# period4 (6.-12.6. 2018)
if [ $period = period4 ];
then    
    year=2018
    yy=18
    month=06
    days=(06 07 08 09 10 11 12)

fi

# period5 (1.-30.4. 2019)
if [ $period = period5 ];
then    
    year=2019
    yy=19
    month=04
    days=(01 02 03 04 05 06 07 08 09 10)
fi

# period6 (1.-30-6-2019)
if [ $period = period6 ];
then    
    year=2019
    yy=19
    month=06
    days=(01 02 03 04 05 06 07 08 09 \
          10 11 12 13 14 15 16 17 18 19 \
          20 21 22 23 24 25 26 27 28 29 30)
fi

}
